Algoritmo "A6ex1-PARA"
// Disciplina   : Lógica de Programação e Algoritmos
// Professor   : MSc. Tiago Antonio da Silva
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vinicius L Silveira
// Data atual  : 21/03/2025
Var

   i: inteiro
   j : inteiro

Inicio


   Para i de 1 até 10 faca

   Escreval("Tabuada do", i)
   Escreval("-----------------")
   
   Para j de 1 até 10 faca
    Escreval(i, " x ", j, " =", (i*j) )
   fimpara
   fimpara
   
Fimalgoritmo