Algoritmo "A6ex1-PARA"
// Disciplina   : Lógica de Programação e Algoritmos
// Professor   : MSc. Tiago Antonio da Silva
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Vinicius L Silveira
// Data atual  : 21/03/2025
Var

   i: inteiro
   numero : inteiro

Inicio

   Escreval("Você quer saber a tabuada de qual número ?")
   Leia(numero)
   
   Para i de 1 até 10 faca
    Escreval(i, " x", numero, " =", (i*numero) )
   fimpara
   
Fimalgoritmo